GET http://localhost:8000/trees

###

GET http://localhost:8000/trees/62cc597772a504d1e2055b54

###

POST http://localhost:8000/trees
Content-Type: application/json

{
    "name": "English Oak"
}

### 

PATCH http://localhost:8000/trees/62cc597772a504d1e2055b54
Content-Type: application/json

{
    "name": "English Yew"
}


### 

DELETE http://localhost:8000/trees/62cc597772a504d1e2055b54
